/* eslint-disable */
// Generated by Wrangler by running `wrangler types counter/worker-configuration.d.ts --config counter/wrangler.jsonc --include-runtime false` (hash: bc7ac01cc2b117ac9948980c2ad3d5a9)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_ORIGIN: "https://nagisanzenin.github.io";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN">> {}
}
